services:
  - type: web
    name: codename
    runtime: node
    plan: free # or starter, standard, etc.
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPSTASH_REDIS_REST_URL
        sync: false # manually set in dashboard
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        sync: false
    healthCheckPath: /

